export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNSUPPORTED_COURIER = 'UNSUPPORTED_COURIER',
  COURIER_API_ERROR = 'COURIER_API_ERROR',
  COURIER_TIMEOUT = 'COURIER_TIMEOUT',
  COURIER_AUTH_ERROR = 'COURIER_AUTH_ERROR',
  ORDER_ALREADY_EXISTS = 'ORDER_ALREADY_EXISTS',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  CANCEL_NOT_ALLOWED = 'CANCEL_NOT_ALLOWED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
